version: "3.9"

services:
  medicin-journal-api:
    build:
      context: .
      dockerfile: ./MedicinJournal.API/Dockerfile
    ports:
      - 9000:80
    volumes:
      - ./MedicinJournal.API/Data:/data
  medicin-journal-ui:
    build:
      context: ./MedicinJournal.UI
      dockerfile: ./Dockerfile
    ports:
      - 9001:80

  
