version: '3.4'

services:
  medicinjournal.api:
    image: ${DOCKER_REGISTRY-}medicinjournalapi
    build:
      context: .
      dockerfile: MedicinJournal.API/Dockerfile
  medicin-journal-ui:
    build:
      context: ./MedicinJournal.UI
      dockerfile: ./Dockerfile
    ports:
      - 9001:80
